// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctbsyucvwpieqyqnojiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0YnN5dWN2d3BpZXF5cW5vaml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMTc1MTksImV4cCI6MjA3NDY5MzUxOX0.2FpkUgRPZ9afrnlBszLwd3FSd01ttuP8ZmC07z1K-K0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});